name: github pages

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: make build
        env:
          PUBLIC_DOMAIN: /pomodoro-party/

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
